ONBOARDING: Dialog with character pressed
priettt/kotlin-marvel pull request #2
Opened 2018-12-14 19:50 UTC by priettt

When clicking a character, a dialog shows up with the character's information

Signed-off by: Francisco Prieto francisco.prieto@globant.com

2018-12-14 20:30 UTC, SartiMau requested changes

2018-12-14 20:30 UTC, SartiMau commented on app/src/main/java/com/puzzlebench/cleanMarvelKotlin/presentation/mvp/CharacterPresenter.kt
> +                    var detailsLink = ""
use constants please

2018-12-14 20:31 UTC, SartiMau commented
Please add a video showing how the app is working with the new functionality

2018-12-14 20:37 UTC, eis6aer commented on app/src/main/java/com/puzzlebench/cleanMarvelKotlin/presentation/mvp/CharacterPresenter.kt
> +                    var detailsLink = ""
I would put the dot on the new line 
```suggestion
                    getCharacterDetailServiceUseCase.invoke(value.id)
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
```

2018-12-14 20:39 UTC, eis6aer commented
I would put the observable operators on a new line each 
```getCharacterDetailServiceUseCase.invoke(value.id)
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())```

2018-12-17 13:11 UTC, priettt commented on app/src/main/java/com/puzzlebench/cleanMarvelKotlin/presentation/mvp/CharacterPresenter.kt
> +                    var detailsLink = ""
done!

2018-12-17 13:28 UTC, SartiMau requested changes

2018-12-17 13:28 UTC, SartiMau commented on app/src/main/java/com/puzzlebench/cleanMarvelKotlin/presentation/adapter/viewholder/viewholder.kt
>          val string = item.thumbnail.path + "." + item.thumbnail.extension
no use constants and use strings templates pls

2018-12-17 13:28 UTC, SartiMau commented on app/src/main/java/com/puzzlebench/cleanMarvelKotlin/presentation/extension/ImageExtensions.kt
> +    if (url != null) Picasso.get().load(url).into(this)
use braces and put each function in a separated line pls

2018-12-17 13:37 UTC, SartiMau approved these changes

2018-12-17 19:39 UTC, SartiMau approved these changes

2018-12-17 19:56 UTC, fanky10 approved these changes
LG2M

2018-12-17 19:56 UTC, merged